services:
  app:
    build: .
    ports:
      - "5005:4000"
    depends_on:
      - db
    tty: true
    env_file:
      - .env

  db:
    image: postgres:16.3-alpine
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    command: postgres
    restart: unless-stopped

volumes:
  postgres_data:

